modLoader="javafml"

loaderVersion="[31,)"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="turtychemistry"

version="1.0"

displayName="Turty's Chemistry Mod"

updateJSONURL="http://myurl.me/"

displayURL="https://turtysproductions.github.io/"

logoFile="examplemod.png"

credits="TurtyWurty, ilja615(for a few textures)"

authors="TurtyWurty and maybe, just maybe, TurtyWurty. Also now that I think of it, TurtyWurty!"

description='''
A mod for minecraft which adds chemistry into the game.
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.turtychemistry]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency

[[dependencies.turtychemistry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
