modLoader="javafml"

loaderVersion="[31,)"

[[mods]]

modId="turtychemistry"

version="1.0"

displayName="Turty's Chemistry Mod"

displayURL="https://turtysproductions.github.io/"

logoFile="logo.png"

credits="TurtyWurty"

authors="TurtyWurty and maybe, just maybe, TurtyWurty. Also now that I think of it, TurtyWurty!"

description='''
A mod for minecraft which adds chemistry into the game.
'''

[[dependencies.turtychemistry]] 
    modId="forge" 
    mandatory=true 
    versionRange="[31,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.turtychemistry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
